### ISSUE TITLE
docklib errors out when run on 10.13.16

### ISSUE THREAD

**Issue by aysiu** [homebysix/docklib#10]
```
/System/Library/LaunchAgents/com.apple.Dock.plist: Could not find specified service
Traceback (most recent call last):
  File "/usr/local/outset/login-once/DefaultDock.py", line 26, in <module>
    dock.save()
  File "/Library/Python/2.7/site-packages/docklib.py", line 61, in save
    if getattr(self, key):
AttributeError: Dock instance has no attribute 'show-recents'
```

Thanks to @WardsParadox for finding the issue, which is `show-recents` not being available until 10.14.

**Comment by WardsParadox** [comment]
Going to add a OS check for that key.
