### ISSUE TITLE
Python3 Compatibility

### ISSUE THREAD

**Issue by WardsParadox** [homebysix/docklib#20]
When attempting to use docklib in a python3 environment, we get this error. I haven't looked into it fully yet, just logging it now.
```
 import docklib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/docklib.py", line 28, in <module>
    class Dock:
  File "/Library/Python/2.7/site-packages/docklib.py", line 68, in Dock
    "dblclickbehavior", "show-recents-immutable", "windowtabbing"
TypeError: append() takes exactly one argument (3 given)
```

**Comment by WardsParadox** [comment]
Fix inbound
